



CREATE TABLE if not exists positions (
                           id BIGINT generated by default as identity primary key,
                           name VARCHAR(150) NOT NULL
);

CREATE TABLE if not exists electronics_types (
                                   id BIGINT generated by default as identity primary key,
                                   name VARCHAR(150) NOT NULL
);

-- Создание справочника "Магазин"
CREATE TABLE if not exists stores (
                        id BIGINT generated by default as identity primary key,
                        name VARCHAR(150) NOT NULL,
                        address TEXT NOT NULL
);

-- Создание справочника "Тип покупки"
CREATE TABLE if not exists purchase_types (
                                id BIGINT generated by default as identity primary key,
                                name VARCHAR(150) NOT NULL
);

-- Создание реестра "Сотрудники"
CREATE TABLE if not exists employees (
                           id BIGINT generated by default as identity primary key ,
                           last_name VARCHAR(100) NOT NULL,
                           first_name VARCHAR(100) NOT NULL,
                           surname VARCHAR(100),
                           birth_date DATE NOT NULL,
                           position_id BIGINT NOT NULL,
                           store_id BIGINT NOT NULL,
                           gender BOOLEAN NOT NULL,
                           CONSTRAINT fk_employee_position FOREIGN KEY (position_id) REFERENCES positions(id),
                           CONSTRAINT fk_employee_store FOREIGN KEY (store_id) REFERENCES stores(id)
);

-- Создание реестра "Электротовары"
CREATE TABLE if not exists electronics (
                             id BIGINT generated by default as identity primary key,
                             name VARCHAR(150) NOT NULL,
                             type_id BIGINT NOT NULL,
                             price NUMERIC(10,2) NOT NULL,
                             quantity INTEGER NOT NULL,
                             archived BOOLEAN NOT NULL,
                             description TEXT,
                             CONSTRAINT fk_electronics_type FOREIGN KEY (type_id) REFERENCES electronics_types(id)
);

-- Создание реестра "Покупки"
CREATE TABLE if not exists purchases (
                           id BIGINT generated by default as identity primary key,
                           electronics_id BIGINT NOT NULL,
                           employee_id BIGINT NOT NULL,
                           store_id BIGINT NOT NULL,
                           purchase_datetime TIMESTAMP NOT NULL,
                           purchase_type_id BIGINT NOT NULL,
                           CONSTRAINT fk_purchase_electronics FOREIGN KEY (electronics_id) REFERENCES electronics(id),
                           CONSTRAINT fk_purchase_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
                           CONSTRAINT fk_purchase_store FOREIGN KEY (store_id) REFERENCES stores(id),
                           CONSTRAINT fk_purchase_type FOREIGN KEY (purchase_type_id) REFERENCES purchase_types(id)
);

-- Таблица
CREATE TABLE if not exists electronics_type_employee (
                                           electronics_type_id BIGINT NOT NULL,
                                           employee_id BIGINT NOT NULL,
                                           PRIMARY KEY (electronics_type_id, employee_id),
                                           CONSTRAINT fk_ete_type FOREIGN KEY (electronics_type_id) REFERENCES electronics_types(id),
                                           CONSTRAINT fk_ete_employee FOREIGN KEY (employee_id) REFERENCES employees(id)
);

-- Таблица "Электротовар-магазин" (связующая таблица между electronics и stores)
CREATE TABLE if not exists electronics_store (
                                   electronics_id BIGINT NOT NULL,
                                   store_id BIGINT NOT NULL,
                                   quantity INTEGER NOT NULL,
                                   PRIMARY KEY (electronics_id, store_id),
                                   CONSTRAINT fk_es_electronics FOREIGN KEY (electronics_id) REFERENCES electronics(id),
                                   CONSTRAINT fk_es_store FOREIGN KEY (store_id) REFERENCES stores(id)
);



--------------------


--Заполнение БД

INSERT INTO  positions (name) VALUES
        ('Manager'),
        ('Cashier'),
        ('Sales Associate'),
        ('Technician'),
        ('Administrator'),
        ('Stock Clerk'),
        ('Customer Service'),
        ('Supervisor'),
        ('Assistant Manager'),
        ('Security');


INSERT INTO electronics_types (name) VALUES
        ('Smartphones'),
        ('Laptops'),
        ('Tablets'),
        ('Televisions'),
        ('Cameras'),
        ('Audio Systems'),
        ('Wearable Devices'),
        ('Gaming Consoles'),
        ('Smart Home Devices'),
        ('Accessories');


INSERT INTO stores (name, address) VALUES
        ('Electro Store 1', '123 Main St, Springfield'),
        ('Electro Store 2', '456 Oak St, Shelbyville'),
        ('Electro Store 3', '789 Pine St, Capital City'),
        ('Electro Store 4', '101 Maple Ave, Ogdenville'),
        ('Electro Store 5', '202 Elm St, North Haverbrook'),
        ('Electro Store 6', '303 Birch St, Springfield'),
        ('Electro Store 7', '404 Cedar St, Shelbyville'),
        ('Electro Store 8', '505 Walnut St, Capital City'),
        ('Electro Store 9', '606 Ash St, Ogdenville'),
        ('Electro Store 10', '707 Cherry St, North Haverbrook');


INSERT INTO purchase_types (name) VALUES
            ('Cash'),
            ('Credit Card'),
            ('Debit Card'),
            ('Online Payment'),
            ('Mobile Payment'),
            ('Check'),
            ('Voucher'),
            ('Wire Transfer'),
            ('Gift Card'),
            ('Other');


INSERT INTO employees (last_name, first_name, surname, birth_date, position_id, store_id, gender) VALUES
        ('Ivanov', 'Ivan', 'Ivanovich', '1985-01-15', 1, 1, true),
        ('Petrov', 'Petr', 'Petrovich', '1990-03-22', 2, 2, true),
        ('Sidorova', 'Anna', 'Sergeevna', '1992-05-10', 3, 3, false),
        ('Smirnov', 'Alexey', 'Alexandrovich', '1988-07-30', 4, 4, true),
        ('Volkova', 'Elena', 'Nikolaevna', '1983-11-12', 5, 5, false),
        ('Kuznetsov', 'Dmitry', 'Igorevich', '1995-09-18', 6, 6, true),
        ('Popova', 'Olga', 'Vladimirovna', '1987-12-05', 7, 7, false),
        ('Sokolov', 'Sergey', 'Petrovich', '1991-04-25', 8, 8, true),
        ('Vasilieva', 'Marina', 'Andreyevna', '1989-06-15', 9, 9, false),
        ('Lebedev', 'Nikolay', 'Fedorovich', '1993-02-02', 10, 10, true);


INSERT INTO electronics (name, type_id, price, quantity, archived, description) VALUES
            ('Smartphone A', 1, 499.99, 50, false, 'Latest model smartphone A'),
            ('Laptop B', 2, 899.99, 30, false, 'High performance laptop B'),
            ('Tablet C', 3, 299.99, 40, false, 'Affordable tablet C'),
            ('LED TV D', 4, 699.99, 20, false, '42 inch LED TV D'),
            ('Camera E', 5, 399.99, 25, false, 'Digital camera E with high resolution'),
            ('Audio System F', 6, 199.99, 35, false, 'Stereo audio system F'),
            ('Smartwatch G', 7, 149.99, 60, false, 'Smartwatch G with health tracking'),
            ('Gaming Console H', 8, 499.99, 15, false, 'Next-gen gaming console H'),
            ('Smart Home Hub I', 9, 129.99, 45, false, 'Smart home hub I with connectivity'),
            ('Accessory J', 10, 29.99, 100, false, 'Wireless accessory J for various devices');


INSERT INTO purchases (electronics_id, employee_id, store_id, purchase_datetime, purchase_type_id) VALUES
         (1, 1, 1, '2025-01-10 10:15:00', 1),
         (2, 2, 2, '2025-01-11 11:20:00', 2),
         (3, 3, 3, '2025-01-12 12:25:00', 3),
         (4, 4, 4, '2025-01-13 13:30:00', 4),
         (5, 5, 5, '2025-01-14 14:35:00', 5),
         (6, 6, 6, '2025-01-15 15:40:00', 6),
         (7, 7, 7, '2025-01-16 16:45:00', 7),
         (8, 8, 8, '2025-01-17 17:50:00', 8),
         (9, 9, 9, '2025-01-18 18:55:00', 9),
         (10, 10, 10, '2025-01-19 19:00:00', 10);

INSERT INTO electronics_type_employee (electronics_type_id, employee_id) VALUES
     (1, 1),
     (2, 2),
     (3, 3),
     (4, 4),
     (5, 5),
     (6, 6),
     (7, 7),
     (8, 8),
     (9, 9),
     (10, 10);

INSERT INTO electronics_store (electronics_id, store_id, quantity) VALUES
    (1, 1, 10),
    (2, 2, 5),
    (3, 3, 8),
    (4, 4, 3),
    (5, 5, 7),
    (6, 6, 12),
    (7, 7, 15),
    (8, 8, 4),
    (9, 9, 9),
    (10, 10, 20);











